### ISSUE TITLE
nmt-rs Multihash compatibility 

### ISSUE THREAD

**Issue by fl0rek** [eigerco/lumina#142]
subtask of #133 

Custom multihash + nmt-rs compatibility https://github.com/celestiaorg/celestia-node/blob/34775bbf11e102f4a2457e09acdfc83c288ded73/share/ipld/nmt.go#L61-L68

**Comment by fl0rek** [comment]
Turns out we have most of the required blocks already in `types/src/byzantine.rs` and we should be able to reuse them when needed.

**Comment by zvolin** [comment]
we only had to read them correctly so far, but if creation will be needed on our side, we don't have it yet.
It's most likely about creating an adapter which will use `nmt_rs::NamespacedSha256Hasher` for the multihash hasher like
https://github.com/multiformats/rust-multihash/blob/master/derive/src/lib.rs#L27
