### ISSUE TITLE
lumina.eiger.co should display some information about node health

### ISSUE THREAD

**Issue by fl0rek** [eigerco/lumina#238]
Following error conditions are currently only conveyed through logs:
- node panicked and died
- new header validation failed (possibly as a result of switching from one private network to another, which will never clear itself)
- we couldn't establish connection with peers (there's only information about number of connected peers)
- valid BEFP received, causing node to stop
- probably more (TODO: what exactly, input welcome)

UX for these situations isn't great - users might notice that there are no new headers coming, but that's mostly it.

We could at least display text "status: healthy", "status: panicked", "status: degraded connection", etc.

**Comment by zvolin** [comment]
I'm closing this as now we have events streaming and they also contain fatal errors of internal components. Also I don't think we need more for our dev setup which is not intended for a big audience
