### ISSUE TITLE
RPC Issue with share_get_eds

### ISSUE THREAD

**Issue by S1nus** [eigerco/lumina#335]
Using share_get_eds [in this codebase](https://github.com/S1nus/fastsync-server/blob/main/src/main.rs#L162). 

Sometimes, it throws this error:
```
RestartNeeded("Networking or low-level protocol error: WebSocket connection error: message too large: len >= 11255879, maximum = 10485760")
```

**Comment by oblique** [comment]
Thanks for your report. Can you test with this change: https://github.com/eigerco/lumina/pull/336
