### ISSUE TITLE
Difference in handling bad encoding fraud proofs to ref implementation

### ISSUE THREAD

**Issue by liamsi** [eigerco/lumina#337]
In the go implementation, `ShareWithProof` has an axis field: https://github.com/celestiaorg/celestia-node/blob/f98d632818d566c7b4fd995b0f4bdc6443a7ed06/share/eds/byzantine/share_proof.go#L29-L30 and befp itself as well: 
https://github.com/celestiaorg/celestia-node/blob/f98d632818d566c7b4fd995b0f4bdc6443a7ed06/share/eds/byzantine/bad_encoding.go#L33
In go, it is used here: https://github.com/celestiaorg/celestia-node/blob/f98d632818d566c7b4fd995b0f4bdc6443a7ed06/share/eds/byzantine/share_proof.go#L36C9-L41

In Rust/lumina, the axis in the shareWithProof is not used as it does not exist: https://github.com/eigerco/lumina/blob/4f2bbc602d9c8921b0d2054af751ed9793456ad0/types/src/byzantine.rs#L185-L188

After chatting with @walldiss, it seems that this was introduced later in node to handle all cases. Would be good if this was on-par with the reference implementation even if this code path will likely never be used 🤞🏼

**Comment by oblique** [comment]
Thanks! It looks like it was introduced with https://github.com/celestiaorg/celestia-node/pull/3306. We will align our implementation.
