### ISSUE TITLE
Allow gRPC clients codegen

### ISSUE THREAD

**Issue by dimazhornyk** [eigerco/lumina#441]
Hey! As gRPC is the main protocol used by Celestia, you need a client code to be generated for a `.proto` definitions (something like [this](https://github.com/astriaorg/astria/blob/main/crates/astria-core/src/generated/celestia.blob.v1.rs#L43)).

The only way to achieve it now is to store all the proto files in any Celestia client implementation, which is a bit unnecessary, especially taking into account that you have a great `celestia-proto` package that could cover that.

[Here](https://github.com/astriaorg/astria/blob/main/tools/protobuf-compiler/src/main.rs#L62) is how it is done in Astria's codebase, it would be great if there was an opportunity to do something similar with `celestia-proto` using a feature flag. It doesn't necessarily have to be tonic and tonic_build, but those are kind of standard, so using them makes the most sense.

Also, here is the minimal list of methods required for a client, I don't remember which exactly, but some of the files weren't included in the list that you compile [here](https://github.com/eigerco/lumina/blob/main/proto/build.rs#L69):

```
use super::{
    celestia_proto::{
        query_client::QueryClient as BlobQueryClient, MsgPayForBlobs,
        QueryParamsRequest as QueryBlobParamsRequest,
    },
    cosmos::{
        auth::{
            query_client::QueryClient as AuthQueryClient, BaseAccount, QueryAccountRequest,
            QueryParamsRequest as QueryAuthParamsRequest,
        },
        base::{
            node::{
                service_client::ServiceClient as MinGasPriceClient,
                ConfigRequest as MinGasPriceRequest,
            },
            v1beta1::Coin,
        },
        crypto::secp256k1,
        tx::v1beta1::{
            mode_info::{Single, Sum},
            service_client::ServiceClient as TxClient,
            AuthInfo, BroadcastMode, BroadcastTxRequest, Fee, GetTxRequest, ModeInfo, SignDoc,
            SignerInfo, Tx, TxBody,
        },
    },
    tendermint::types::{Blob as PbBlob, BlobTx},
};
```

**Comment by zvolin** [comment]
generating proto files was implemented in #454. We're still working on a proper grpc client (already available but treat it as a very bare bone / early alpha)
