### ISSUE TITLE
Getting blobs?

### ISSUE THREAD

**Issue by lzrscg** [eigerco/lumina#479]
Hey all, hope you are well. Curious what the status is for being able to get blobs directly from the network without connecting to a Go node (i.e. `Get` https://node-rpc-docs.celestia.org/?version=v0.20.4#blob fully in the browser with no dependencies)? At a glance, it seems this is unsupported, but thought I would ask here just to be sure.

Thanks in advance 🙏

**Comment by zvolin** [comment]
Hey, currently[ we support getting all blobs from a given](https://docs.rs/lumina-node/latest/lumina_node/node/struct.Node.html#method.request_all_blobs) namespace. It's not yet exposed in npm package, but should be addressed soon with https://github.com/eigerco/lumina/pull/468. Getting by commitment is not yet supported at all (it's not supported by shwap protocol) but it can be implemented technically with some overhead.

**Comment by lzrscg** [comment]
Thanks this is just what I was looking for!
