### ISSUE TITLE
Remove workaround for incorrect RPC response from go-jsonrpc

### ISSUE THREAD

**Issue by fl0rek** [eigerco/lumina#53]
During RPC calls go celestia node returns invalid (JSON-RPC-wise) responses for following calls:
- `p2p.BlockPeer`
- `p2p.ClosePeer`
- `p2p.Connect`
- `p2p.Protect` (but _not_ `p2p.Unprotect`)
- `p2p.UnblockPeer`
and probably others.
 
In general it seems like `jsonrpsee` is unhappy with the calls that have `Returns: Null` in [docs](https://docs.celestia.org/api/v0.11.0-rc8). On success these send a response without a required `result` field:
```
Custom error: Unparseable message: {\"id\":3,\"jsonrpc\":\"2.0\"}")'
```

As a workaround, we can send these as notifications. Node still executes remote call, but response isn't expected, so `jsonrpsee` doesn't enter error state. This has an obvious downside of ignoring any errors that might actually come back. Once we no longer need to accommodate this behaviour, workaround should be removed.

Relevant issue in `celestia-node`: https://github.com/celestiaorg/celestia-node/issues/2460
and in `go-jsonrpc`: https://github.com/celestiaorg/celestia-node/issues/2460

**Comment by zvolin** [comment]
This just got merged in the rpc server celestia is using: https://github.com/filecoin-project/go-jsonrpc/issues/102#event-12741125149
