### ISSUE TITLE
Harden Exchange Server against malicious actors spamming it with requests

### ISSUE THREAD

**Issue by fl0rek** [eigerco/lumina#90]
ExchangeServerHandler spawns new tasks for Store operations for most of the received requests. Investigate ways of mitigating danger of us getting overwhelmed by huge number of requests.

libp2p allows us to limit number of incoming streams negotiating the connection
https://docs.rs/libp2p/latest/libp2p/swarm/struct.SwarmBuilder.html#method.max_negotiating_inbound_streams

for the connected streams we can track the number of in-flight requests and drop the `ResponseChannel` to close the connection, if we're getting overwhelmed.

**Comment by zvolin** [comment]
this is now not needed as we no longer spawn but put futures in FuturesUnordered. connection limits is separate case tracked in https://github.com/eigerco/lumina/issues/330
